### ISSUE TITLE
Random filenames confuse the Micro.blog cache

### ISSUE THREAD

**Issue by manton** [svendahlstrand/plugin-search-space#2]
I noticed while doing some server maintenance that my blog has thousands of files like this:

```
www.manton.org/search-space/documents.78564716335d8d49bb7114329a118c9d.json
www.manton.org/search-space/documents.78a460683d7a3867cb1b8e26dab331e0.json
www.manton.org/search-space/documents.78a95871a71ae52fcf92797bb357627e.json
www.manton.org/search-space/documents.78bc13044e81edb15202de8bedb3fcd3.json
www.manton.org/search-space/documents.78e331cc99d966877d0fdc2ee65b32b9.json
```

I haven't looked closely but I assume it's this line with the MD5 hash:

https://github.com/svendahlstrand/plugin-search-space/blob/1aa940e31dcf3d6b7f0f329ce5080d624e77d0f9/layouts/shortcodes/search-space/documents-url.html#L2

While this _should_ be fine, in reality Micro.blog caches generated files for a while, so they stick around. It's not causing any performance problems but doesn't seem ideal.

I haven't thought through any specific suggestions to change this. Just pointing out the problem. 🙂

**Comment by svendahlstrand** [comment]
Haha, that's funny! That's to aid the heavy client-side caching I'm doing to spare your servers from unnecessary network traffic. Mission accomplished, but instead I'm unknowingly taking up disk space. 😅 Hugo's asset pipeline, with support for fingerprinting, is awesome, and I naively assumed it handled cleanup automatically. Sorry about that!

I will figure out a different scheme for when to do cache busting. For example, I can output the last build date as a data attribute and fetch the documents when there's a new build.

Sorry again, and thanks for the report.

**Comment by svendahlstrand** [comment]
I went with adding the md5 hash as a query parameter instead. Can you confirm that 1.0.1 fixes the thousands-of-files problem, @manton? 😊

**Comment by manton** [comment]
Looks good! 👍
