### ISSUE TITLE
Cannot get nav item to appear

### ISSUE THREAD

**Issue by RickCogley** [svendahlstrand/plugin-search-space#5]
Hello - testing out search space, and for whatever reason I cannot get the nav item to appear. 

I created a page, and updated its url to "/search-space" but, it won't appear. 

Any idea what I might be doing wrong? Do I need to put anything in the body of the page? Or, do I need a page at all?

**Comment by svendahlstrand** [comment]
Hi Rick, thanks for checking out my plug-in. 🙏 Search Space is automatically available after installation at the URL https://cogley.jp/search-space/. But it will not add itself to your blog's navigation. It's up to you to link to the page however you want.

How to add arbitrary URLs to the navigation in Micro.blog is [described over at the help center](https://help.micro.blog/t/redirects/70). In short, create a new page and paste the URL in the page's content.

**Comment by RickCogley** [comment]
Ah right, I didn't have the fqdn in there, just the path. Thanks & donated!
